import { env } from '@/env.mjs'

export const siteConfig = {
  name: 'Omar Maysara',
  title: 'Omar Codes | Full Stack Developer',
  description:
    "Hello, I'm Omar. I am full stack developer from Belgium. I enjoy building sites and apps. My focus is React (Next.js).",
  keywords: [
    'Omar Maysara',
    'Full Stack Developer',
    'Belgium',
    'React',
    'Next.js',
    'Web development',
    'Full Stack',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'TypeScript',
    'Node.js',
    'Express',
    'PostgreSQL',
    'MySQL',
    'Tailwind CSS',
    'Shadcn UI',
    'HTML',
    'CSS',
    'Git',
    'GitHub',
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Netlify',
    'Vercel',
    'Linux',
    'Docker',
  ],
  creator: 'Omar Maysara',
  url: '#',
  contact: {
    email: 'omar.bussiness@gmail.com',
    linkedin: '#',
    github: 'https://github.com/CodeArmour',
  },
  links: {
    contactForm: '/#contact',
    linkedin: '#',
    github: 'https://github.com/CodeArmour',
    mailTo: 'mailto:omar.bussiness@gmail.com',
    cvPdf: '#',
  },
}